import { type NextPage } from "next";
import { signIn, signOut, useSession } from "next-auth/react";
import Head from "next/head";
import Image from "next/image";
import { useState } from "react";
import Button from "~/components/Button";
import FormGroup from "~/components/FormGroup";
import Input from "~/components/Input";
import { api } from "~/utils/api";

const GeneratePage: NextPage = () => {
  const [form, setForm] = useState({
    prompt: "",
  });
  const [imageUrl, setImageUrl] = useState<string>();
  const session = useSession();
  const isLoggedIn = !!session.data;
  const generateIcon = api.generate.generateIcon.useMutation();

  const updateForm = (key: string) => {
    return function (e: React.ChangeEvent<HTMLInputElement>) {
      setForm((prev) => ({
        ...prev,
        [key]: e.target.value,
      }));
    };
  };

  const handleSubmit = (e: React.FormEvent) => {
    e.preventDefault();
    generateIcon
      .mutateAsync(form)
      .then((data) => {
        setImageUrl(data.b64Image);
      })
      .finally(() => {
        setForm({ prompt: "" });
      });
  };

  return (
    <>
      <Head>
        <title>Create T3 App</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <main className="flex min-h-screen flex-col items-center justify-center">
        {isLoggedIn ? (
          <Button onClick={() => signOut().catch(console.error)}>Logout</Button>
        ) : (
          <Button onClick={() => signIn().catch(console.error)}>Login</Button>
        )}

        {session.data?.user.name}
        <form className="flex flex-col gap-4" onSubmit={handleSubmit}>
          <FormGroup>
            <label>Prompt</label>
            <Input value={form.prompt} onChange={updateForm("prompt")} />
          </FormGroup>
          <Button>Submit</Button>
        </form>
        {imageUrl && (
          <Image
            src={`data:image/png;base64,${imageUrl}`}
            alt={form.prompt}
            width={100}
            height={100}
          />
        )}
      </main>
    </>
  );
};

export default GeneratePage;
